### ISSUE TITLE
[BUG]: Registry initialization error

### ISSUE THREAD

**Issue by spiliti** [Sunbird-RC/community#164]
### What is the bug related to?

Registry CLI

### What went wrong?

I ran the Registry init command with the following environment:

Docker version 20.10.8, build 3967b7d28e
docker-compose version 1.29.2, build unknown
Node: v16.13.1

using default example, I got the following error:

 Successfully copied over necessary files
✖ An unexpected error occurred while starting the registry: Command failed with exit code 125: docker-compose up -d

### What did you expect to see?

A bug should not have happened, instead ... for sure

**Comment by gamemaker1** [comment]
Hi @spiliti,

Could you please run `docker compose up` in the same directory and paste the output? Thanks.

**Comment by spiliti** [comment]
Please close this. I have e-installed docker-compose and the problem "disappered". Thanks
