### ISSUE TITLE
Issuance Portal - Configuring document/VC

### ISSUE THREAD

**Issue by jayadinni** [Sunbird-RC/community#209]
As an issuer, I would like to view and select existing document types and templates available, to issue VC.

https://user-images.githubusercontent.com/580711/160987561-ce7e3075-5654-4326-99ef-d5456a000981.mp4

1. Flow: View Dashboard -> Click 'Add document' -> Select Template or upload new template -> Save Document
2. Save Document: Default name of the document would be the 'document type' selected.
![image](https://user-images.githubusercontent.com/580711/161471691-0eb6755a-cdef-4b5f-8871-69d7e223c820.png)
Later releases: Edit Template

**Comment by pramodkvarma** [comment]
Great!

**Comment by Renuka-S** [comment]
Closing this issue. As basic functionality mentioned above is supported. Enhancements can be tracked here. https://github.com/Sunbird-RC/community/issues/634
