### ISSUE TITLE
Mobile number validation missing on Teacher registration form

### ISSUE THREAD

**Issue by TawareAditya** [Sunbird-RC/community#26]
Accept less than real mobile number count. It should be validated with proper mobile number format and may have a country code.

Kindly check for the Student registration form.

https://user-images.githubusercontent.com/90304141/132680002-ba339cbc-e9d4-425c-9ba2-db8bb2fde0b5.mp4

**Comment by MaheshKulkarniTekdi** [comment]
@TawareAditya Please see if you can have the user story under which this bug got reported.

**Comment by TawareAditya** [comment]
> @TawareAditya Please see if you can have the user story under which this bug got reported.

This is related to the Teacher registration workflow and seems the user story is not added yet. I will make this change once the story is added.

**Comment by TawareAditya** [comment]
This is fixed and confirmed on https://ndear.xiv.in/
