### ISSUE TITLE
Attestation workflow: Generating PDF for single entry

### ISSUE THREAD

**Issue by Renuka-S** [Sunbird-RC/community#264]
Currently, we only provide W3C VCs

**Comment by Sreejit-K** [comment]
Steps to replicate : 

UseCase : 

We have two schema (Official and Insurance)
Officail can issue and insurance certificate and the insurance schema has all the attestaionPolicies and credential templates necessary for VC issuance and attestation flows.

1. Make sure you have your have "credentialTemplate" with in your "attestationPolicies" of your schema.
2. Create an official 
3. Get the official token 
4. Use this token to issue a credential 
5. Get the VC using the credential id.
6. Now use the credential-schema search API using tags (curl --location 'http://localhost:3333/credential-schema?tags=Insurance'). Use this to fetch the credential-schema
7. Using this credential-schema-id create a template (curl --location 'http://localhost:3333/template' \
--header 'Content-Type: application/json' \
--header 'Cookie: JSESSIONID=B0DD505E879A453DC435F93D60676010' \
--data '{
    "schemaId": "did:schema:3a310bbf-947f-4e6f-afae-af407403c045",
    "schemaVersion": "1.0.0",
    "template": "<html lang='''en'''><head><meta charset='''UTF-8''' /><meta http-equiv='''X-UA-Compatible''' content='''IE=edge''' /><meta name='''viewport''' content='''width=device-width, initial-scale=1.0''' /><script src='''[https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'/''>](https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'/''%3E)</script><link rel='''stylesheet''' href='''style.css''' /><title>{{policyName}}Certificate</title></head><body><div>{{policyName}}</div><img src='''{{qr}}''' alt='''Base64 Imag'''></body></html>",
    "type": "Handlebar"
}')
8. Now use this template ID to fetch the credential 
9. Use the same get API that you have used to fetch the credential but the difference now is in the headers change the "Accept" from 'application/json' to 'application/pdf' or 'text/html'
10. you will receive the VC as a PDF/ html.
