### ISSUE TITLE
[BUG]:  Registry CLI fails if ran on docker-compose v2 

### ISSUE THREAD

**Issue by tushar5526** [Sunbird-RC/community#312]
### What is the bug related to?

Registry CLI

### What went wrong?

[A bug happened!](https://github.com/docker/compose/issues/8630#issuecomment-1141930536)

### What did you expect to see?

It should support docker-compose or prompt to install docker-compose plugin.

**Comment by tejash-jl** [comment]
@tushar5526 
https://docs.sunbirdrc.dev/developer-documentation/installation-guide

**Comment by tushar5526** [comment]
Hi @tejash-jl , apologies for the badly formatted issue report. 

The `registry-cli` was trying to run docker-compose commands as `docker compose up` instead of `docker-compose up`. There was a `-` missing. 

On further investigation, I found that the former command is available through [compose-plugin](https://docs.docker.com/compose/install/linux/). `pip install docker-compose` does not support `docker compose up` it requires commands to start with `docker-compose` with a `-` in between.

**Comment by tejash-jl** [comment]
https://docs.docker.com/compose/install/
