### ISSUE TITLE
[BUG]: Get entity by Bearer token is not working

### ISSUE THREAD

**Issue by tushar5526** [Sunbird-RC/community#327]
### What is the bug related to?

Registry Core

### What went wrong?

I can get the entity by `osid` and through `search` but cannot fetch entity details using the authorization token and `/api/v1/{entityName}` endpoint. 

https://docs.sunbirdrc.dev/api-reference/registry/get-an-entity -- roles and inviteRoles are set to `anonymous`

 

### What did you expect to see?

I expect the entity details but I am getting response of `entity not found`.

**Comment by tejash-jl** [comment]
@tushar5526 remove `anonymous` for `roles`

**Comment by tushar5526** [comment]
Hi @tejash-jl, thank you for the fast reply. I am getting 401 unauthorized with the `access token` that I got from keycloak after removing roles - `anonymous` from the schema. Can you point me to the right docs? I am not able to find much on the website.

**Comment by tushar5526** [comment]
PS: `access-token` is working as I am able to fetch user info from keycloak using that token from the endpoint. 

```
http://<server_ip>:8080/auth/realms/sunbird-rc/protocol/openid-connect/userinfo
```
fetches me the user-name, email etc. from keycloak.. but same token with registry is not working.

**Comment by tejash-jl** [comment]
> Hi @tejash-jl, thank you for the fast reply. I am getting 401 unauthorized with the `access token` that I got from keycloak after removing roles - `anonymous` from the schema. Can you point me to the right docs? I am not able to find much on the website.

https://docs.sunbirdrc.dev/learn/faqs#the-registry-is-throwing-unauthorized-issues-401-on-retrieving-entity.-the-registry-throws-getaddrin

**Comment by tushar5526** [comment]
https://stackoverflow.com/questions/61966384/keycloak-invalid-token-issuer

I had this issue, which was resolved using the above setup. But, I am still facing the same `401` unauthorized issue when I hit `/api/v1/<entityName>` using the `access_token` of that entity generated from keycloak. 

PS: I am able to get data from keycloak using that same `token`. There is nobody in the response just `401` unauthorized error and no headers specifying the issue. Apart from that `registry` logs shows no errors but the following warning. 

![image](https://user-images.githubusercontent.com/30565750/213361369-f3a97ba3-ea27-4e52-a0d3-9d5bf4417df8.png)

**Comment by tushar5526** [comment]
Any suggestions?

**Comment by ChakshuGautam** [comment]
@tejash-jl Can we please look into this?

**Comment by tejash-jl** [comment]
@tushar5526, since you're accessing keycloak over an IP address the SSL check, is mandatory,
you can turn that off in keycloak admin console: https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/realms/ssl.html

**Comment by tushar5526** [comment]
Thanks for reply. @tejash-jl I have disabled ssl on both master and sunbird-rc realm already. 
![image](https://user-images.githubusercontent.com/30565750/217461296-878b3a44-6346-4a93-8c84-284a447b42d7.png)

![image](https://user-images.githubusercontent.com/30565750/217461393-5b3c13bc-c574-4e94-b285-ed1d459f141f.png)

I can generate the access token through FA, authorize it and request information through FA, but same token is failing when I hit sunbird rc API `/api/v1`

Please see the screenshots here https://github.com/UPHRH-platform/lr-service/issues/5

**Comment by tejash-jl** [comment]
@tushar5526 can you share the logs of registry

**Comment by tejash-jl** [comment]
@tushar5526 you can ping me on the discord channel, and we can get on a call to resolve the issue.

**Comment by tushar5526** [comment]
Pinging you there @tejash-jl

**Comment by tushar5526** [comment]
Hey @tejash-jl this was fixed after setting up SSL for registry service at 8081 port. Closing this issue.

**Comment by SnehaVeer** [comment]
Hi @tushar5526 could you please give us step wise guide to setup the SSL for registry service at 8081 port? I'm facing same issue.
