### ISSUE TITLE
Support hard delete in core

### ISSUE THREAD

**Issue by parthlawate** [Sunbird-RC/community#371]
Currently, only soft delete functionality is supported.
We need to provide an option via an env flag to switch between hard/soft delete (the default is soft delete).
When a hard delete is executed, the respective record from all the respective tables and from ES needs to be removed/deleted.

**Comment by chopadetejaswini** [comment]
Implementation steps :
1. understand the Soft delete code in project, difference between hard delete and soft delete
2. understand about config variable and set it
3. study the code of soft delete
4. write code for hard delete
5. test the hard delete

**Comment by chopadetejaswini** [comment]
tried hard delete using OsGrapg, Graph, Transaction but removeVertex() of Graph and rollbackTransaction() of DataProvider showing error- cannot resolve method. So will tring to solve this error

**Comment by chopadetejaswini** [comment]
write logic for hard delete, set variable / flag , but in Postman its showing response OK but when I tried to check database its showing soft delete even Hard delete enable is true, so trying to solve this

**Comment by chopadetejaswini** [comment]
I have to get sign data from JSON node and need to convert to string so in RegistryEntityController

**Comment by chopadetejaswini** [comment]
Now hard delete function is worked on database and deleted entity will add in revocation list, revocation list table name is RevokedCredentialto

**Comment by chopadetejaswini** [comment]
Started working for Support hard delete for Elastic Search, Write hard delete code in ElasticServiceImpl class, In ElasticSearchActor add delete case for both Soft and hard delete, in this used if condition , for hard delete wrote getDeleteType() in ESMessage class and added getter setter methods. In application.yml file make search - Provder name -ElasticSearchService

**Comment by chopadetejaswini** [comment]
I want to make some changes in code, I tried for this and make some changes but now my project build is failed so trying to solve that issue

**Comment by chopadetejaswini** [comment]
now project build failed error is overcome, trying to run soft delete  API, working on that

**Comment by chopadetejaswini** [comment]
Hard delete is working, trying for Soft delete, not able to find deleted flag in ES after call Delete API, facing nullPointerException cause jsonNode was not able to get osSigned data solved that exception

**Comment by chopadetejaswini** [comment]
Trying to for soft delete, whenever I try to call DELETE API its shows successful response but record is not deleting logically even the Environment variable set false

**Comment by chopadetejaswini** [comment]
Task is completed, now Hard delete supports DB and ES both, will raise the PR today

**Comment by chopadetejaswini** [comment]
Raised PR

**Comment by srprasanna** [comment]
@holashchand  can you review this PR and close?

**Comment by holashchand** [comment]
PR https://github.com/Sunbird-RC/sunbird-rc-core/pull/276
