### ISSUE TITLE
Registry to start emitting events

### ISSUE THREAD

**Issue by varadeth** [Sunbird-RC/community#380]
[https://github.com/orgs/Sunbird-RC/discussions/356](https://github.com/orgs/Sunbird-RC/discussions/356)

- [ ] Configuration for Private & Internal fields.
- [ ] Mask or Hash the Private & Internal fields based on configuration
- [ ] Send all public and masked or hashed private & internal fields to kafka producer
- [ ] Create a metric service which has a kafka consumer for emitted events
- [ ] Define Clickhouse schema for each entityType
- [ ] Store values in clickhouse with the event details
- [ ] Build an API for which returns aggregation of a table from config values

**Comment by rhwarrier** [comment]
Here's what we'll use for a first cut of the dashboards:

Total Issuers
Types of VCs

Total VCs issued
No. Of VCs split by Type

Total no. of recipients
Recipients split by gender

**Comment by tejash-jl** [comment]
https://sunbirdrc-sandbox.xiv.in/dashboard/eer
dashboard url

**Comment by parthlawate** [comment]
@tejash-jl is this the Emit based dashboard now ? 

Getting a login page. Is it not public ?

**Comment by varadeth** [comment]
> @tejash-jl is this the Emit based dashboard now ?
> 
> Getting a login page. Is it not public ?
@parthlawate yes this is emit based dashboard. you can visit the public link [https://sunbirdrc-sandbox.xiv.in/public/dashboards/ezgFN5jlbnWCOe8dD6I1JbuUXeDsTq9Pj7s0Lh8N?org_slug=default](https://sunbirdrc-sandbox.xiv.in/public/dashboards/ezgFN5jlbnWCOe8dD6I1JbuUXeDsTq9Pj7s0Lh8N?org_slug=default)

**Comment by Pritzz4** [comment]
Which email id and password should I use to login

**Comment by sukhpreetsamagra** [comment]
How can I view this?

Are we using this implementation in the reference solution implementation @snehalpatil 

cc - @chakshugautam

**Comment by tejash-jl** [comment]
we have used this in EER reference implementation,
https://docs.sunbirdrc.dev/developer-documentation/metrics
