### ISSUE TITLE
Sunbird RC in action- Implementation & Possibilities

### ISSUE THREAD

**Issue by manukalia29** [Sunbird-RC/community#434]
- [x] Possibilities
- [x] Implementations

**Comment by manukalia29** [comment]
Prepared a list of Implementations and asked Rajeesh to give approval.

**Comment by manukalia29** [comment]
Approval Pending

**Comment by sukhpreetsamagra** [comment]
Can you post this here? @manukalia29

**Comment by manukalia29** [comment]
https://rc.sunbird.org/learn/adopters
