### ISSUE TITLE
join two schemas

### ISSUE THREAD

**Issue by tejash-jl** [Sunbird-RC/community#452]
join two schemas while adding an entity
an entity can refer to another entity being already created

for eg
Teacher
{
   "name": "Deepak Rana"
}
assume the osid of this teacher to be 123-123

student can refer to this entity in the following way
Student 
{
    "name": "Chaitanya Pandit"
    "references": "did:Teacher:123-123"
}

when we search for student, the referred entity i.e Teacher will also be returned in response

**Comment by Sreejit-K** [comment]
@srprasanna  @holashchand Here are my observations - 

- If the reference doesn't exist in the system it stores and returns it as a string. 
- On updating the entity with an existing reference entity it updates and returns the reference entity
- _**One Issue I found out is the visibility scope - the private fields of the reference entity are getting exposed, this should be handled.**_
- And also need a round of discussion on 

> - should it return specific fields of the referred entity? - we can add refernceFeilds to return in the osConfig and make corresponding changes
> - or return the whole entity with out the private fields - have to add the filter layer on the reference nodes using the reference entity Type

can you please add your comments on these. Thanks!

**Comment by Sreejit-K** [comment]
Unable to update the exiting PR linked to this ticket so attaching the new PR here - https://github.com/Sunbird-RC/sunbird-rc-core/pull/277
