### ISSUE TITLE
Not able to configure Sunbird-Rc core to run properly

### ISSUE THREAD

**Issue by Akshat121203** [Sunbird-RC/community#48]
Unable to find, how keycloak needs to be configured.
Not able to find API specification

**Comment by parthlawate** [comment]
@dileepbapat could you assist with this please?

**Comment by dileepbapat** [comment]
Please setup keycloak using configuration : https://github.com/Sunbird-RC/sunbird-rc-core/tree/main/infra

Swagger API documentation is also available as an endpoint as mentioned in https://docs.sunbirdrc.dev/learn/technical-specification-draft

**Comment by rahul101001000** [comment]
Thanks @dileepbapat, will try out the keycloak config mentioned here. 

So Swagger API docs are after I get it installed. Chicken and egg - I'd like to review the API before I get it installed. Suggestion - Why not post a Swagger YAML in the repo and link it from the tech-spec-draft.
