### ISSUE TITLE
Teacher Basic Detail form - unable to submit

### ISSUE THREAD

**Issue by TawareAditya** [Sunbird-RC/community#53]
**Describe the bug**
Nothing happens when clicking Submit button. Found some errors in the console.

**To Reproduce**
1. Go to Teacher's Basic Detail form
2. Fill up all required fields
3. Check the Submit button appear to enable
4. Click Submit button and observe

**Expected behavior**
The fields details should get save and the form should get submit

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome
 - Version 93

**Comment by code-blooded-guy** [comment]
Able to submit it, Please try with new user

**Comment by TawareAditya** [comment]
> Able to submit it, Please try with new user

It is working now with a new user.
