### ISSUE TITLE
 Enable & Fix issues for 'Add document' functionality in issuance portal (Add Template Functionality in EER)

### ISSUE THREAD

**Issue by chaitrali-r** [Sunbird-RC/community#582]
- Read all properties from schema and add varibale in creadentialsTemplate to set that variable in certificate html.
- this credential Template object update and genrate dynamically
- if user remove/add the property  creadentialsTemplate object should be updated.

**Comment by jayadinni** [comment]
Are we looking for adding template in EER? as its currently handled in backend.
Suggest to first fix it in core (issuance portal) and then bring it to ref-implementation

**Comment by Pratikshakhandagale** [comment]
![Image](https://user-images.githubusercontent.com/16133636/233906436-fc1fa3a2-b395-4e24-811c-7ece12fa15e9.png)

-Read all properties from schema and add varibale in creadentialsTemplate to set that variable in certificate html.
- this credential Template object update and genrate dynamically
- if user remove/add the property creadentialsTemplate object should be updated.

**Comment by Pratikshakhandagale** [comment]
**Are we looking forward to add template through interface/frontend in EER? as it's currently handled in backend.
Suggest to first fix it in core (issuance portal) and then bring it to ref-implementation**
- Yes, using frontend we can add template but if there any change request come, From frontend we can't edit it as we dont have edit template functionality implemented yet so there is dependency on backend. thats why in EER template are updated from backend. To fix this issue we added task in github [link](https://github.com/Sunbird-RC/community/issues/368). we will pickup this in upcomming sprint.

- Also priviously, we wasn't support the upload my template (svg/html) from frontend, Using this feature user can easily upload html/svg template and write schema for new VC. Now, we are support this feature in issuance - [link](https://github.com/Sunbird-RC/community/issues/209) 

- only one issue is pending, creating dynamically list of properties in creadential template which is used on vc certificate to show student info. This one issue, Im tring to fix under this task.

once all above tasks are done, we can easily create/update the template from frontend.

Once this functionality done and  tested on issuance we will bring to EER.

**Comment by Renuka-S** [comment]
Multiple issues got added here, for better understanding and related enhancements to this can be tracker here https://github.com/Sunbird-RC/community/issues/634
