### ISSUE TITLE
[FEAT]: Send out notifications when credential is generated

### ISSUE THREAD

**Issue by varadeth** [Sunbird-RC/community#626]
### What is the feature request for?

Registry Core

### What problem/inconvenience (if any) will this feature solve?

Registry should be able to send out notifications even when the credential is created or updated.

### Describe the feature clearly.

Current version of Registry sends notifications only when the actor is invited to the system. There is no notification that can be sent if the credential is issued or credential is updated. This feature should enable that functionality to send out a notification to actor on the operations of create update of credentials

- [x] Get template from the Schema. If not present, the get the default template
- [x] Formulate a message that needs to sent to actor
- [x] Send out a notification using APIs
- [x] Configure a way that notification can be sent via messaging queue based on configuration
- [x] Tests
- [x] Documentation

**Comment by Renuka-S** [comment]
@varadeth Can you share below details if we have thought about this?
1. Can you share the notificate sample template. 
2. Also does this include notification when claim has been raised or approved?
3. where can each issuer need to setup the configs for the SMS, tokens etc? Have we thought of this UI?

**Comment by tejas-hv** [comment]
Documentation is also added
