### ISSUE TITLE
[BUG] : Not able to get login window of digilocker -  after getting logout from previous user

### ISSUE THREAD

**Issue by Pritams43** [Sunbird-RC/community#628]
**Steps to Reproduce**

- Login to the digilocker
- Click on allow
- Click on Logout
- Go to issuer login again
- Click on digilocker login again

- Redirecting to the this window only 

![Image](https://user-images.githubusercontent.com/118895138/233915837-876a3843-a7be-4e1b-ab02-729abb9b01a0.png)

**Comment by tejash-jl** [comment]
@Pritzz4 digilocker meripehchaan is storing the logged in status,
its not in our control
