### ISSUE TITLE
[BUG]: Certificate width and height is not getting change after adding schema fields - It should get change

### ISSUE THREAD

**Issue by Pritzz4** [Sunbird-RC/community#689]
Before Adding the schema fields certificate width and height getting change 

**Steps to reproduce**

- Go to add new tamplate
- Click on my template
- upload the html/svg file 
- Click on edit template 
- Click on open style manager icon
- Go to the dimension 
- Change the size of certificate
- Click on advnace editor
- add schema fields
- Click again on open style manager icon
- Try to change the size again

**Comment by suvarnakale** [comment]
@Pritzz4 This issue is not reproducing.
