### ISSUE TITLE
[NHA]: Feature to share credentials of a Pledge on social media

### ISSUE THREAD

**Issue by Sreejit-K** [Sunbird-RC/community#718]
### What is the feature request for?

Other

### Describe the feature clearly.

Functionality is yet to be decided. But the basic overview is to be 

- The user should be able to show some infographics that might have just the name and organs that he/she donated, without any QR code
- It should be shareable on social media 

The finalized requirement from NHA is still pending. For now, this can be added to the backlog

**Comment by tejash-jl** [comment]
Duplicate task of https://github.com/Sunbird-RC/community/issues/601
