### ISSUE TITLE
[FEAT]: Create an API for updating VC for an entity

### ISSUE THREAD

**Issue by srprasanna** [Sunbird-RC/community#743]
### What is the feature request for?

Registry Core

### What problem/inconvenience (if any) will this feature solve?

An API to update the VC for a Entity. The older VC should be revoked. 

### Describe the feature clearly.

Create an API to update the VC for an entity. The older VC should be revoked.

**Comment by chopadetejaswini** [comment]
Understanding: I should write API for Update the verfied Credentials for an entity and once VC is updated older VC should be revoked(canceled).

Implementation steps: 
Understand the exact concept of VC.
Understand othet API's code related to VC
implement logic for update request of VC
write the functions related to update API in relevent class
Test the code if its working or not
Commit the code once done
Raise the PR

**Comment by chopadetejaswini** [comment]
Today I have read about Verified credentials from documentation, refer util/sign API from RegistryUtilsController class and revoke API from RegistryEntityController class, try to create update API for VC but its not completed

**Comment by chopadetejaswini** [comment]
@srprasanna I have write @PutMapping API code in RegistryEntityController Class, have created updateExistingVC() in RegistryHelper class and implement that method. Created UPDATED_CREDENTIAL variable in Constants class and UPDATE_VC variable in Response class. there is no runtime or compilation error but whenever I tried to call the API through Postman its showing errormsg -"vc: do not exist". please help me for the same

**Comment by chopadetejaswini** [comment]
On today I have changed the code of RegistryControllerClass,

 firslty i have change the url and make it as " /api/v1/{entityName}/{entityId}/vc," and http request as POST

  I have called revokeExistingCredentials() of class registryHelper .
 means the existing credential is deleted means ossigned  data will be null so we have to fill this empty signed data with newly 
 generated signature for that:
 called sign() of class SignatureService class in RegistryEntityController.
After created new credential entity should be updated so for that:
called updateEntity() of RegistryService class in RegistryHelper by cretating new function updateExistingVC() 
 then that new function is called in RegistryEntityController class after sign()
 
but when I called the method in postman its showing error - "errmsg": "Unable to reach service: 400 Bad Request: [{\"error\": \"Bad Request\", \"message\": Bad request}]"

**Comment by chopadetejaswini** [comment]
Sunbird RC - Working on create Update API for VC- Today I have used revokeAnEntity() instead of revokeExistingCredential() to revoke the existing ossigned data.
then sign() created the new ossigned data. I have made changes for updateEntity. I have used activateShard() of ShardManager instead of getShard(). Now the issue is that whenever i called the PUT API for first time it shows Recordnotfound Exception and when I called the same API for second time it shows response 200 ok.

**Comment by chopadetejaswini** [comment]
Today I have created new function updateAnEntity in RegistryHelper class. in which I have passed a variable in which result of sign() is stored. means newly generated ossigned data has passed. and called that Method controller class.
 but while calling API its showing errormsg: Unable to reach service: 400 Bad Request: [{\"error\": \"Bad Request\", \"message\": Bad request

**Comment by chopadetejaswini** [comment]
Yesterday I have changed the RegistryEntityController class and sign() removed in RegistryHepler class by creating function updateVc(). So in RegistryHelper updateVc(),  is responsible for signing the entity data, adding the cryptographic signature to the JSON data, and then updating the entity in the registry by providing the updated JSON data to the registryService.updateEntity method.but when I calling API its showing error: unable to reach service, 400 bad request

**Comment by chopadetejaswini** [comment]
When I calling the API its showing response 200 Ok.but when I called revokeAnEntity() ossigned data is not becoming empty so trying for that so result can be correct

**Comment by chopadetejaswini** [comment]
@srprasanna @Sreejit-K @Renuka-S When I calling the API of put its showing response 200 Ok.Verified credential is getting updated , I have checked with get API and database also. Its working perfectly fine with database. But its not going to update in ElasticSearch. So do I need to update it in elasticsearch also? if yes then will work for that also

**Comment by chopadetejaswini** [comment]
Now When I call the put API for VC verified credential is getting updated in ES and DB , for that I need to downgrade the ES image as 6.6.0. But as per the discussion with holash he told me that we don't need to create new API for update VC we can make changes in existing API of update with entityId, we tried for that on today but there was several issues so we need to solve them

**Comment by chopadetejaswini** [comment]
When I calling the API its showing response 200 Ok.VC get updated in database and in  ElasticSearch also. as per suggested by Holash will tried to use existing update API (using entity id) to update the VC instead of using this new API.and its working now

**Comment by chopadetejaswini** [comment]
Raised PR

**Comment by chopadetejaswini** [comment]
https://drive.google.com/file/d/1l1DnVxFOW3ZGjjxiYvytctu0NGf1mj1M/view?usp=sharing

Link of output

**Comment by srprasanna** [comment]
@holashchand  can you review and close this after looking at the PR.

**Comment by srprasanna** [comment]
Issue is resolved.
