### ISSUE TITLE
Use the web did based id, to check if current resolver can resolve web based did

### ISSUE THREAD

**Issue by manukalia29** [Sunbird-RC/community#888]

**Comment by srprasanna** [comment]
This should also ensure that we generate DIDs similar to did:web:https://<base_url>/<schema-id>/<entity_id>

**Comment by holashchand** [comment]
PR: https://github.com/Sunbird-RC/sunbird-rc-core/pull/279

**Comment by srprasanna** [comment]
Resolved.
