### ISSUE TITLE
[FEAT]: Missing API Endpoint to fetch the Revocation-List in the credential services

### ISSUE THREAD

**Issue by Sreejit-K** [Sunbird-RC/community#904]
### What is the feature request for?

Registry Core

### What problem/inconvenience (if any) will this feature solve?

It is inconvenient for me to do .... If we add this feature, it would make it easier to do ....

### Describe the feature clearly.

Add the missing endpoint for the revocation-list in the credential services, as the Agri-stack team will be requiring this to test their flow as per the meeting that we had on 20th of December.

**Comment by Sreejit-K** [comment]
https://github.com/Sunbird-RC/sunbird-rc-core/pull/273

**Comment by srprasanna** [comment]
What about changes in 1.0?

**Comment by Sreejit-K** [comment]
@srprasanna We have a dedicated "RevokedCredential" schema which provides all the API's necessary for discovery. Do we need to add something else? cause the existing APIs can be used to fetch the RevockedCredentials list.

**Comment by manukalia29** [comment]
@Sreejit-K  Please check whether they are following the W3C API

**Comment by Sreejit-K** [comment]
The existing PR checks for the verifiable credentials which are in Revocked status. This list can be used for offline verification - the W3C specification for revocation list concentrates more on online verification - https://github.com/Sunbird-RC/sunbird-rc-core/pull/273
