### ISSUE TITLE
Deploy SunBird VC 2.0 on unified-dev env

### ISSUE THREAD

**Issue by Sreejit-K** [Sunbird-RC/community#908]
### What is the feature request for?

Registry Core

### Description

Digit is planning to integrate Sunbird-RC credentials services to generate verifiable QR's, which can be added to existing certificate generation flow in the digit environment. To kick start this interoperability, we need to deploy the RC credential services in their unified-dev environment. 

- [x]  Give KT to Mithun & Aniket on RC credentials services
- [x] Write helm charts to deploy the RC credential services.
- [x] Co-ordinate and create a namespace for RC 2.0 services and deploy the services.
   

https://digit-discuss.atlassian.net/browse/DPG-2162

**Comment by manukalia29** [comment]
@Sreejit-K Please add the description also

**Comment by Sreejit-K** [comment]
Hi @srprasanna, Can you please let me know where I can push the Helm-charts for 2.0 services. So that I could add the instruction for setup and close this ticket. Thanks!

**Comment by srprasanna** [comment]
Add Helms under a new folder helms/v2/<helm-charts>. Repo is https://github.com/Sunbird-RC/deployment

**Comment by Sreejit-K** [comment]
Have added the helm-charts and raised the PR. https://github.com/Sunbird-RC/deployment/pull/1. Closing the ticket as it is merged.
